---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd-dev
  name: bgd-dev
  namespace: bgd-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd-dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgd-dev
    spec:
      containers:
      - image: quay.io/rhdevelopers/bgd:1.0.0
        name: bgd-dev
        env:
        - name: COLOR
          value: "blue"
        resources: {}
---
